# Generated by Django 3.2.16 on 2022-12-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizeduser',
            name='library_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='authorizeduser',
            name='position',
            field=models.CharField(blank=True, choices=[('Chief Librarian', 'Chief Librarian'), ('Head of Acquisitions', 'Head of Acquisitions')], max_length=100),
        ),
    ]
