# Generated by Django 3.2.16 on 2022-12-18 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialMaterial',
            fields=[
                ('informationmaterial_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.informationmaterial')),
                ('ISSN', models.CharField(blank=True, max_length=30)),
                ('issue_number', models.PositiveIntegerField()),
                ('volume_number', models.PositiveIntegerField()),
                ('serial', models.CharField(max_length=100)),
                ('publish_date', models.DateField(blank=True)),
            ],
            bases=('resources.informationmaterial',),
        ),
        migrations.AddField(
            model_name='printmediamaterial',
            name='edition',
            field=models.CharField(blank=True, choices=[('Revised', 'Revised'), ('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth'), ('Seventh', 'Seventh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='printmediamaterial',
            name='ISBN',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='SerialPrintMediaMaterial',
        ),
    ]
