# Generated by Django 3.2.16 on 2022-12-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_remove_serialmaterial_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printmediamaterial',
            name='ISBN',
            field=models.CharField(max_length=30),
        ),
    ]
